version: "3.9"

services:
  db:
    image: postgres:14.22-alpine3.22
    container_name: postgres
    restart: always

    ports:
      - "${DB_PORT}:5432"

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - db_data:/var/lib/postgresql/data

    deploy:
      resources:
        limits:
          cpus: "${DB_CPUS}"
          memory: ${DB_MEMORY}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    networks:
      - postgres_net   


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always

    ports:
      - "5050:80"

    env_file:
      - .env

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      - db

    networks:
      - postgres_net


volumes:
  db_data:
  pgadmin_data:

networks:
  postgres_net:
    external: true